In [5]:
py_list=[1,2,3,4,5]

In [6]:
py_list

[1, 2, 3, 4, 5]

In [7]:
#never use list as a variable 
list={1,2,3,4,5}

In [8]:
import numpy as np

In [9]:
np_array = np.array(py_list)

In [10]:
np_array 

array([1, 2, 3, 4, 5])

In [11]:
np_array +1 #np works with all elements 

array([2, 3, 4, 5, 6])

In [12]:
py_list + [1]

[1, 2, 3, 4, 5, 1]

In [13]:
py_list*2 #how come you cant add a number to list but u can mulitply it 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [14]:
np_array*2

array([ 2,  4,  6,  8, 10])

In [23]:
np_array +1 

array([2, 3, 4, 5, 6])

In [16]:
len(np_array)

5

In [17]:
np_array.shape

(5,)

In [18]:
my_rand_numbers= np.random.randint(0,100,100)

In [19]:
mask = (my_rand_numbers < 50)

In [20]:
my_rand_numbers

array([ 4, 87, 56, 28, 63, 23, 16, 68, 13, 23, 71, 42, 87,  2, 13, 62, 77,
       57, 49, 41, 30, 36,  5, 80, 36, 70, 92, 64, 47, 31, 42, 32, 96, 23,
       80, 61, 96, 82, 42, 50, 70, 46, 63, 42, 14, 26, 85, 19, 36, 78, 43,
       42, 45, 43, 15, 75, 47, 59, 43, 70,  0, 35, 23, 96, 21, 72, 23,  3,
       65, 54, 69, 83, 80, 98, 62, 26, 43, 13, 34, 54, 80, 27, 91, 15, 80,
       43,  2, 27, 70, 28, 21, 24, 72, 85, 95, 70, 75, 13, 32,  4])

In [21]:
my_rand_numbers[1] #python starts counting from 0

np.int64(87)

In [22]:
my_rand_numbers[-1]

np.int64(4)