<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

In [1]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [2]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [3]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [4]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

In [ ]:
# dictionary has key and values input 

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

## 2.1 Size

In [7]:
import numpy as np
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [8]:
len(py_list_2d)
len(np_array_2d)
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [9]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [11]:
py_list


[1, 1.5, 'A']

In [12]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [13]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [15]:
np_array +10 #works for np but not py 

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [17]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [18]:
np_array_1+np_array_2

array([11, 22, 33, 44, 55])

In [19]:
py_list_1+py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

## 2.5 Multiplying by a Number

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [20]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [22]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [24]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [27]:

np_array == 3  


array([False, False,  True, False, False])

In [28]:
py_list == 3     # Works, but what IS the question?


False

In [29]:

np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [30]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)

## Footnotes